# Generated by Django 4.2.16 on 2024-12-10 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(help_text='When the flight is scheduled to depart.')),
                ('arrival_time', models.DateTimeField(help_text='When the flight is scheduled to arrive.')),
                ('airline', models.ForeignKey(help_text='The airline operating this flight.', on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='final_project.airline')),
                ('destination', models.ForeignKey(help_text='The destination airport of the flight.', on_delete=django.db.models.deletion.CASCADE, related_name='arriving_flights', to='final_project.airport')),
                ('origin', models.ForeignKey(help_text='The originating airport of the flight.', on_delete=django.db.models.deletion.CASCADE, related_name='departing_flights', to='final_project.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="The passenger's first name.", max_length=50)),
                ('last_name', models.CharField(help_text="The passenger's last name.", max_length=50)),
                ('flight', models.ForeignKey(help_text='The flight this passenger is booked on.', on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='final_project.flight')),
            ],
        ),
    ]
