# Generated by Django 4.2.16 on 2024-10-23 23:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0003_alter_statusmessage_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mini_fb.statusmessage')),
            ],
        ),
    ]
